### PR TITLE
Fix the issue templates of the repo

### PR DESCRIPTION
**Pull request by renatho**
Some fixes for this previous PR: #38
These fixes are on another PR because the other was already merged. 

- Ask for both this plugin and core plugin versions.
- Remove contributing reference as this specific plugin does not have one.
- Update plugin name in the comments to this instead of the core plugin name.

**After the approval, these changes will be replicated to the other repos**

### CODE REVIEW

**Comment by donnapep** [comment]
@renatho I added some additional sections to the PR template that will hopefully save me some manual work.

**Comment by renatho** [comment]
I'm sorry about the delay to answer. It's still on my queue :)

Thank you @donnapep! Good idea in turn explicit about the hooks and deprecation codes!

I was also thinking about another thing while working on some issues and PRs. Maybe we could use the titles as:

### Title

instead of:

#### Title

So in some cases, we can create subsections being still readable. Does it make sense to you?

**Comment by donnapep** [comment]
@renatho Yup, makes sense to me!

**Comment by donnapep** [comment]
Merging as this is good enough for now.

**Comment by renatho** [comment]
> Merging as this is good enough for now.

Perfect! I'll keep it on my pile to work on that after the enrolments project :)

**Comment by renatho** [comment]
@donnapep Thank you for your contributions and suggestions on this! I worked on the replication now. 
You should be receiving a lot of code reviews request. Sorry about that! 😅

**Pull request merged**
